### ISSUE TITLE
你好,我运行报错了,能给说明一下原因吗

### ISSUE THREAD

**Issue by yangyiyuan** [wuyifan18/spider#1]
result = (True, func(*args, **kwds))
  File "spider.py", line 243, in fun
    page_count, count = getCount('1', date, a, ip, '')
  File "spider.py", line 215, in getCount
    count, _ = f(page + ',' + date + ',' + area + ',' + ip + ',' + court)
  File "spider.py", line 185, in f
    page, date, area, proxies, court = para.split(',')
ValueError: too many values to unpack (expected 5)

**Comment by wuyifan18** [comment]
@yangyiyuan 应该是因为默认开启了ip代理，我改一下。

**Comment by yangyiyuan** [comment]
`id: 5613, date: 2016-01-02, area: 北京市, total_count: 0, done: 1/1, using time: 2.25
id: 5613, date: 2016-01-02, area: 天津市, total_count: 0, done: 1/1, using time: 1.12
id: 5613, date: 2016-01-02, area: 上海市, total_count: 0, done: 1/1, using time: 9.15
id: 5613, date: 2016-01-02, area: 重庆市, total_count: 0, done: 1/1, using time: 1.90
id: 5613, date: 2016-01-02, area: 河北省, total_count: 2, done: 1/1, using time: 0.74
id: 5613, date: 2016-01-02, area: 山西省, total_count: 2, done: 1/1, using time: 1.68
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 1/3, using time: 2.63
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 2/3, using time: 2.68
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 3/3, using time: 7.80
id: 5613, date: 2016-01-02, area: 吉林省, total_count: 4, done: 1/1, using time: 2.59
id: 5613, date: 2016-01-02, area: 黑龙江省, total_count: 1, done: 1/1, using time: 1.51
id: 5613, date: 2016-01-02, area: 江苏省, total_count: 7, done: 1/1, using time: 2.39
id: 5613, date: 2016-01-02, area: 浙江省, total_count: 0, done: 1/1, using time: 1.11
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 1/4, using time: 5.83
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 2/4, using time: 3.03
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 3/4, using time: 2.29
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 4/4, using time: 2.68
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "spider.py", line 245, in fun
    page_count, count = getCount('1', date, a, ip, '')
  File "spider.py", line 216, in getCount
    count, _ = f(page + ',' + date + ',' + area + ',' + ip + ',' + court)
  File "spider.py", line 193, in f
    infodata, htmldata = spider.getData(page=page, date=date, area='法院地域:' + area, court='中级法院:' + court)
  File "spider.py", line 128, in getData
    htmldata = self.getDetails(infodata)
  File "spider.py", line 141, in getDetails
    key = getkey(format_key_str).encode('utf-8')
  File "/Users/ewan/works/spider/utils/docid.py", line 106, in getkey
    return re.findall('KEY="(\w+)"', c.eval(''))[0]
  File "/usr/local/lib/python3.7/site-packages/execjs/_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/usr/local/lib/python3.7/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Unexpected keyword 'return'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "spider.py", line 280, in <module>
    for d in pool.imap(fun, iter(t)):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
execjs._exceptions.ProgramError: SyntaxError: Unexpected keyword 'return'`

**Comment by yangyiyuan** [comment]
id: 5613, date: 2016-01-02, area: 北京市, total_count: 0, done: 1/1, using time: 2.25
id: 5613, date: 2016-01-02, area: 天津市, total_count: 0, done: 1/1, using time: 1.12
id: 5613, date: 2016-01-02, area: 上海市, total_count: 0, done: 1/1, using time: 9.15
id: 5613, date: 2016-01-02, area: 重庆市, total_count: 0, done: 1/1, using time: 1.90
id: 5613, date: 2016-01-02, area: 河北省, total_count: 2, done: 1/1, using time: 0.74
id: 5613, date: 2016-01-02, area: 山西省, total_count: 2, done: 1/1, using time: 1.68
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 1/3, using time: 2.63
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 2/3, using time: 2.68
id: 5613, date: 2016-01-02, area: 辽宁省, total_count: 30, done: 3/3, using time: 7.80
id: 5613, date: 2016-01-02, area: 吉林省, total_count: 4, done: 1/1, using time: 2.59
id: 5613, date: 2016-01-02, area: 黑龙江省, total_count: 1, done: 1/1, using time: 1.51
id: 5613, date: 2016-01-02, area: 江苏省, total_count: 7, done: 1/1, using time: 2.39
id: 5613, date: 2016-01-02, area: 浙江省, total_count: 0, done: 1/1, using time: 1.11
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 1/4, using time: 5.83
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 2/4, using time: 3.03
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 3/4, using time: 2.29
id: 5613, date: 2016-01-02, area: 安徽省, total_count: 33, done: 4/4, using time: 2.68
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "spider.py", line 245, in fun
    page_count, count = getCount('1', date, a, ip, '')
  File "spider.py", line 216, in getCount
    count, _ = f(page + ',' + date + ',' + area + ',' + ip + ',' + court)
  File "spider.py", line 193, in f
    infodata, htmldata = spider.getData(page=page, date=date, area='法院地域:' + area, court='中级法院:' + court)
  File "spider.py", line 128, in getData
    htmldata = self.getDetails(infodata)
  File "spider.py", line 141, in getDetails
    key = getkey(format_key_str).encode('utf-8')
  File "/Users/ewan/works/spider/utils/docid.py", line 106, in getkey
    return re.findall('KEY="(\w+)"', c.eval(''))[0]
  File "/usr/local/lib/python3.7/site-packages/execjs/_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/usr/local/lib/python3.7/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/usr/local/lib/python3.7/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Unexpected keyword 'return'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "spider.py", line 280, in <module>
    for d in pool.imap(fun, iter(t)):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
execjs._exceptions.ProgramError: SyntaxError: Unexpected keyword 'return'

**Comment by yangyiyuan** [comment]
@wuyifan18

**Comment by wuyifan18** [comment]
我没遇到过这个问题
